// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenPositionService;

#nullable disable

namespace RecruitmentManagementSystemDb.Migrations
{
    [DbContext(typeof(RecruitmentMgmtSystemDbContext))]
    partial class RecruitmentMgmtSystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CandidateProfileStatusService.Models.CandidateProfile", b =>
                {
                    b.Property<string>("CandidateID")
                        .HasColumnType("text");

                    b.Property<string>("CandidateName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurrenAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurrentCTC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExpectedCTC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("JobID")
                        .HasColumnType("bigint");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NoticePeriod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PermanenetAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimarySkills")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecondarySkills")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("YearOfExperience")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CandidateID");

                    b.ToTable("CandidateProfiles");
                });

            modelBuilder.Entity("CandidateProfileStatusService.Models.OfferDetail", b =>
                {
                    b.Property<string>("CandidateID")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfJoining")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JobID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OfferedCTC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OfferedCompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CandidateID");

                    b.ToTable("OfferDetails");
                });

            modelBuilder.Entity("OpenPositionService.V1.Models.OpenPosition", b =>
                {
                    b.Property<long>("JobId")
                        .HasColumnType("bigint");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<int>("NoOfPositions")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PostedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Qualification")
                        .HasColumnType("text");

                    b.Property<string>("SkillSet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("YearOfExp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("JobId");

                    b.HasIndex("JobTitle")
                        .IsUnique();

                    b.ToTable("OpenPositions");
                });
#pragma warning restore 612, 618
        }
    }
}
